### ISSUE TITLE
Advancements feature

### ISSUE THREAD

**Issue by AlmostPanda** [qwertyuioplkjhgfd/SlimefunAdvancements#11]
Hi, I would like to ask if its possible to turn off the achievements in advancements menu, because I would like to use only slimefun missions.

**Comment by qwertyuioplkjhgfd** [comment]
Set use-advancements-api to false in config.yml

**Comment by AlmostPanda** [comment]
Well.. I can still see it (yes I did a restart)
![image](https://github.com/qwertyuioplkjhgfd/SlimefunAdvancements/assets/141587317/def08a31-5f23-4e48-bcaf-e88a994778e3)

**Comment by AlmostPanda** [comment]
Nvm I fixed that, ty for your help.
