### ISSUE TITLE
Advancement  hide

### ISSUE THREAD

**Issue by AlmostPanda** [qwertyuioplkjhgfd/SlimefunAdvancements#13]
Is there an option to hide the advancement messages when I complete any mission?

![image](https://github.com/qwertyuioplkjhgfd/SlimefunAdvancements/assets/141587317/b0c93ce0-3998-464e-ab03-5a815269ce9f)

**Comment by qwertyuioplkjhgfd** [comment]
don't think so, i can add that though

**Comment by AlmostPanda** [comment]
please lmk when it will be added, ty

**Comment by qwertyuioplkjhgfd** [comment]
added
