### ISSUE TITLE
Slimefun category visibility

### ISSUE THREAD

**Issue by AlmostPanda** [qwertyuioplkjhgfd/SlimefunAdvancements#14]
Is it possible to hide the advancements category in slimefun guide? Because I want to open the gui only with command

![image](https://github.com/qwertyuioplkjhgfd/SlimefunAdvancements/assets/141587317/ef64c6b0-fc5b-4658-991b-fc45fa4635f4)

**Comment by qwertyuioplkjhgfd** [comment]
done

**Comment by qwertyuioplkjhgfd** [comment]
that's weird, try restarting again maybe the plugin didn't update

**Comment by AlmostPanda** [comment]
sure, no problem

**Comment by qwertyuioplkjhgfd** [comment]
hopefully it gets fixed sometime soon, just restart your server twice once that happens then it should work
