### ISSUE TITLE
Mission Ideas

### ISSUE THREAD

**Issue by AlmostPanda** [qwertyuioplkjhgfd/SlimefunAdvancements#15]
I would have some ideas on how to improve the creation of missions with which I would like to share, maybe I will come up with more later. 

1. Would it be possible to add option to move the criteria in mission? I would like to move it in the middle of the mission and under it Reward (you can see on photo). - Probably movable with placeholder or something like that.

2. Option to change the color in the criteria.name

3. Remove the empty line above the criteria.name because I hate it and its killing my mission look

4. Add something like flags: - HIDE_ATTRIBUTES to hide attributes like Attack Damage + Attack Speed on tools

![image](https://github.com/qwertyuioplkjhgfd/SlimefunAdvancements/assets/141587317/d443b9fa-9a13-4ac5-88ae-8574d2cbdf3e)

Let me know what you think about it.

**Comment by qwertyuioplkjhgfd** [comment]
implemented, thanks for the suggestions
you can specify a line in the lore of the display item that is just `%criteria%` and it will be replaced by the criteria progress in both menus (vanilla gui won't have progress due to technical limitation)
