### ISSUE TITLE
Vanilla Advancement Trees

### ISSUE THREAD

**Issue by CamperSamu** [qwertyuioplkjhgfd/SlimefunAdvancements#5]
I'd like to only use the vanilla menu to display advancements and it would be cool if I can chain advancements together like the vanilla ones to make advancement trees to help my players to figure out how to progress.

**Comment by CamperSamu** [comment]
Just saw the note in the readme about trees...
Well at least there's an issue to track this feature at least 😅

**Comment by JustAHuman-xD** [comment]
This feature is possible Char just needs to add it to the Read me, to use this feature add:
`parent : [advancement id]`
to your advancements in the yml
or leave it blank for it to default to the group start

**Comment by JustAHuman-xD** [comment]
For example:
`parent:
  group: slimefun
  display:
    type: CRAFTING_TABLE
    name: "&aExample Parent"
    lore:
      - "This is an example Parent"
  name: "&a[Example Parent]"
  criteria:
    enhanced_crafting:
      name: "parent"
      type: multiblock
      multiblock: ENHANCED_CRAFTING_TABLE
  
child:
  group: slimefun
  parent: parent
  display:
    type: COPPER_DUST
    name: "&aExample Child"
    lore:
      - "This comes after the parent"
  name: "&a[Example Child]"
  criteria:
    dust:
      name: "child"
      type: inventory
      item:
        type: COPPER_DUST`

**Comment by CamperSamu** [comment]
Oh, thanks a lot!
Closing my issue then!
