### ISSUE TITLE
Added advancement criteria

### ISSUE THREAD

**Issue by Azakaturan** [qwertyuioplkjhgfd/SlimefunAdvancements#7]
Would it be possible to maybe be able to have something you could put into the advancements to have it consume x item when it completes the advancement?  For example:

carbonado:
  group: basic
  display:
    type: CARBONADO
    name: "&aShiny darkness"
    lore:
      - "Create a carbonado diamond"
  name: "&a[Shiny darkness]"
  criteria:
    carbonado:
      name: "Obtain carbonado"
      type: inventory
      item: CARBONADO
   consume: true

**Comment by qwertyuioplkjhgfd** [comment]
you could have the advancement reward take the item with a command

i don't think vanilla has a command for that (other than /clear which clears all items of that type) but i'm sure some utility plugin has something like that
