### ISSUE TITLE
group hiding

### ISSUE THREAD

**Issue by 44wrw44** [qwertyuioplkjhgfd/SlimefunAdvancements#8]
Is there any way to hide these groups in the achievement drawer?
![image](https://user-images.githubusercontent.com/73754757/199687181-4dd368fa-81b1-419d-a6cb-26f6507e7d9e.png)

**Comment by qwertyuioplkjhgfd** [comment]
you can disable the api entirely in the config but no way to disable individual ones currently
i may add that option later

**Comment by 44wrw44** [comment]
@qwertyuioplkjhgfd sad, but then you can add the invisible function to the groups, it is in the achievements themselves

**Comment by qwertyuioplkjhgfd** [comment]
wait i might have misunderstood your issue
do you want to remove the group? you can remove the entry in `groups.yml`
unless you want to make the group invisible but still exist, then please reply
