### ISSUE TITLE
Startup Advancement Spam

### ISSUE THREAD

**Issue by ghost** [qwertyuioplkjhgfd/SlimefunAdvancements#9]
When someone first logs into the server, there's a chat spam of advancements which are basically just stating the list of advancement categories that exist. Is there a way to disable that, or could a way to disable that be added?

**Comment by qwertyuioplkjhgfd** [comment]
could you send an example of how that looks?

**Comment by GingerAiyle** [comment]
![sfa_console_ingame](https://user-images.githubusercontent.com/118949867/203692890-947c9f05-86c9-4c53-a2e3-6cf510894a0f.png)


User will log in and then you get this in console/chat

**Comment by qwertyuioplkjhgfd** [comment]
i think i fixed it, lmk if it isn't
